services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./QuestionnaireApp:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    container_name: php
    expose:
      - "9000"
    ports:
      - "8081:9000"
    volumes:
      - ./QuestionnaireApp:/var/www/html
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql
    platform: linux/x86_64
    ports:
      - "3307:3306" # host:container
    environment:
      MYSQL_ROOT_PASSWORD: nikol15
      MYSQL_DATABASE: questionnaire_db
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  default:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
